# D213 Task 2 Rev 1 - Mattinson

## Install required packages

## Import required packages

In [1]:
import pandas as pd
import numpy as np
#import tensorflow as tf
#from tensorflow import keras
#from tensorflow.keras import layers
#from tensorflow.keras.preprocessing.text import Tokenizer
#from tensorflow.keras.preprocessing.sequence import pad_sequences
#import nlp
#import nltk

In [45]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

## Read data files

In [23]:
# read three .csv files - with headers UTF-8
# had to do some minor edits in EXCEL first
amazon = pd.read_csv('data/amazon.csv')
imdb =  pd.read_csv('data/imdb.csv')
yelp =  pd.read_csv('data/yelp.csv')

## Combine dataframes

In [24]:
# add a col 'source' to remember where the data came from
amazon['Source'] = 'Amazon'
imdb['Source'] = 'Imdb'
yelp['Source'] = 'Yelp'

In [25]:
# combine three dataframes
df = pd.concat([amazon, imdb, yelp])

In [26]:
# rename columns, if not already done
df = df.rename(columns={0: 'Sentence', 1: 'Score'})

In [27]:
# reset index 0..2999
df = df.reset_index(drop=True)

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   Sentence  3000 non-null   object
 1   Score     3000 non-null   int64 
 2   Source    3000 non-null   object
dtypes: int64(1), object(2)
memory usage: 70.4+ KB


In [33]:
# show sample from dataframe
df.iloc[::333, :]

Sentence  Score  Source
0     So there is no way for me to plug it in here i...      0  Amazon
333   It fits comfortably in either ear, the sound i...      1  Amazon
666                                         Nice Sound.      1  Amazon
999   You can not answer calls with the unit, never ...      0  Amazon
1332        To call this movie a drama is ridiculous!        0    Imdb
1665  Unless you're just out to visually "collect" a...      0    Imdb
1998                               Exceptionally bad!        0    Imdb
2331  Both of them were truly unbelievably good, and...      1    Yelp
2664                                Eclectic selection.      1    Yelp
2997  Overall I was not impressed and would not go b...      0    Yelp

## Natural Language (Prasad, 2020) week 1

In [38]:
# define sentences - training data
sentences = list(df['Sentence'])

In [51]:
tokenizer = Tokenizer(num_words = 100, oov_token="<OOV>")
tokenizer.fit_on_texts(sentences)
word_index = tokenizer.word_index
sequences = tokenizer.texts_to_sequences(sentences)
padded = pad_sequences(sequences)
#print(word_index)
#print(sequences)
print(padded)

[[ 0  0  0 ... 61  5  1]
 [ 0  0  0 ...  1 92  1]
 [ 0  0  0 ... 13  2  1]
 ...
 [ 0  0  0 ... 14 76 70]
 [ 0  0  0 ...  1  1 41]
 [ 0  0  0 ...  1  2  1]]


In [49]:
# test data
test_data = [
    ' i really love my dog',
    'my dog loves my mom'
    'you love my mom',
    'do you think my do is amazing?'
]

In [50]:
test_seq = tokenizer.texts_to_sequences(test_data)
print(test_seq)

[[4, 48, 78, 17, 1], [17, 1, 1, 17, 1, 78, 17, 1], [94, 22, 1, 17, 94, 6, 1]]


## tensorflow.org

In [56]:
!pip install tensorflow_hub

In [57]:
!pip install tensorflow_datasets

In [59]:
import numpy as np
import tensorflow as tf
import tensorflow_hub as hub
import tensorflow_datasets as tfds
import matplotlib.pyplot as plt

print("Version: ", tf.__version__)
print("Eager mode: ", tf.executing_eagerly())
print("Hub version: ", hub.__version__)
print("GPU is", "available" 
      if tf.config.list_physical_devices('GPU') 
      else "NOT AVAILABLE")

Version:  2.9.1
Eager mode:  True
Hub version:  0.12.0
GPU is NOT AVAILABLE
